### ISSUE TITLE
from CTPN_lib.bbox.nms import nms ModuleNotFoundError: No module named 'CTPN_lib.bbox.nms'

### ISSUE THREAD

**Issue by Agiroy4712** [Mountchicken/CTPN_CRNN_ChineseOCR_PyQt5#1]
hello, I had trouble running the program, can you help me?

![图片](https://user-images.githubusercontent.com/62510641/124060004-a847f080-da5e-11eb-9ce9-3620e3d01711.png)
Traceback (most recent call last):
  File "D:\实验\交互式实验\代码\CTPN_CRNN_ChineseOCR_PyQt5-main\main_gui.py", line 11, in <module>
    from inference import *
  File "D:\实验\交互式实验\代码\CTPN_CRNN_ChineseOCR_PyQt5-main\inference.py", line 16, in <module>
    from CTPN_lib.rpn_msr.proposal_layer import proposal_layer
  File "D:\实验\交互式实验\代码\CTPN_CRNN_ChineseOCR_PyQt5-main\CTPN_lib\rpn_msr\proposal_layer.py", line 3, in <module>
    from CTPN_lib.bbox.nms import nms
ModuleNotFoundError: No module named 'CTPN_lib.bbox.nms'

**Comment by Mountchicken** [comment]
The missed file has been uploaded. And the problem of "No module named 'CTPN_lib.bbox.nms' is quite annoying. The nms code is written in cython, and you can try 'cd utils/bbox ; sh make.sh'

**Comment by Mountchicken** [comment]
check https://github.com/eragonruan/text-detection-ctpn/issues/378

**Comment by Agiroy4712** [comment]
3q~ I follow it，but it doesn't work.... Then i use 'import nms' to replace it, although it don't appear mistake, but i got a new problem: that was when it start just a few second after I click initializing it end. I was run it in pycharm in windows.
![图片](https://user-images.githubusercontent.com/62510641/124127050-db65a080-daad-11eb-8714-8560f3add757.png)

Another I run the inference.py  the problem it shows. I think the reason is also the nms problem. 0.0
![图片](https://user-images.githubusercontent.com/62510641/124127131-f1736100-daad-11eb-996e-34be5ac28415.png)

**Comment by Mountchicken** [comment]
see the updated readme, build environment section.  Also, remember to check your email.
